# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban_card_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('in-process', 'in-process'), ('done', 'done')], default='to-do', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Kanban_card_1.Card'),
        ),
    ]
