# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kanban_card_1', '0002_auto_20180921_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('card', 'name')]),
        ),
    ]
